name: GreatScoot
favicon: null
layout_spectrum: 0.17288930108770728
typography_spectrum: 0.17468587402254343
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafeff'
    - '#091135'
    - '#6cff87'
    - '#4b555e'
    - '#c09187'
  brandStrength: 0.5625
  lightness: 0.9941980477888137
  saturation: 0.3390423331875354
  rhythmicContrast: 0.25
purpose: []
